### ISSUE TITLE
wavelength dependent gamma

### ISSUE THREAD

**Issue by elizaleung830** [laserfun/laserfun#62]
This is a great libary! Just wondering if it is possible to define wavelength dependent gamma? Since gamma can varies with large mode sizes.

**Comment by DanHickstein** [comment]
That's a good question. Looking at line 147 of nlse.py, it seems that gamma is being applied in the frequency domain. So, naively, gamma could easily be an array with a unique gamma for each frequency. 

I have no idea if that's the right thing to do from a math/physics perspective, but it certainly seems reasonable to implement in the code. Would you have any way to benchmark if a wavelength-dependent gamma functionality was doing what you wanted it to do?

```python
r = 1j * gamma * w * m * exp(-lin_operator*z)  # full RHS of Eq. (3.13)
```

https://github.com/laserfun/laserfun/blob/master/laserfun/nlse.py#L147

**Comment by elizaleung830** [comment]
Hi,

I am trying to reproduce figure 4a from [this paper](https://opg.optica.org/ol/abstract.cfm?uri=ol-44-6-1492). My code can be seen in [this link](https://github.com/elizaleung830/SC-generation-stimulation/blob/master/SCG_Stimulation/Benchmark/laserfun/Juanjuan%202019/code/Figure4a.ipynb). 

I have tried using an array for gamma but not sure if I did it in the right way. I assume the wavelength grid is a linspace start from center_wavelegnth * 0.25 and end at center_wavelength * 4. Also, the the temporal graph doesn't look quite right when I do so.

**Comment by DanHickstein** [comment]
In your code, you'd setting the `gamma_function` to be a function of wavelength. However, it's supposed to be a function of `z`, the position along the waveguide/fiber. So, that capability isn't going to help you with the wavelength dependent gamma.

The code isn't designed with a wavelength dependent gamma in mind. But, I think that it might work anyway. 

Look on line [147 of nlse.py](https://github.com/laserfun/laserfun/blob/master/laserfun/nlse.py#L147), where we see that gamma is getting multiplied by `w`, which is an array of (angular) frequencies in (I think) THz. (w = 2*pi*f). 

You'll want to look at the `w` array and see that the frequencies are. There is an fftshift that happens on line [113](https://github.com/laserfun/laserfun/blob/master/laserfun/nlse.py#L113), and on lines 105-109 different things happen to w depending on if the shock term is applied. If the shock term is turned on, then I believe that the `w` array should just be the actual angular frequencies, though the fft shift might mean that they are in a weird order. Anyway, I think that you'll just need to supply a gamma array that matches these angular frequencies. 

Again, I don't know if this approach is really scientifically valid. Maybe @cfredrick or @ycasg can tell us if using a wavelength-dependent gamma can be easily implemented in this type of NLSE code.

**Comment by cdfredrick** [comment]
You're going to want to initialize gamma onto the same frequency grid as defined in the pulse object. You can get the angular frequency grid "$`\omega`$" from the ``w_THz`` property of the pulse. After interpolating your effective areas onto that grid you should be good to set $`\gamma = \omega \, n_2/c \, A_{eff}`$.

Getting into the math/physics of it, I do think a wavelength-dependent gamma is a valid approximation. The shock term you may or may not be familiar with is actually a first-order implementation of that. $\gamma$ is usually defined as a constant, where all parameters are evaluated at $\omega = \omega_0$. As seen in equation 2 of Dudely's "Supercontinuum generation in photonic crystal fiber", the shock term is associated with $\gamma$ and a time derivative: $`\gamma \, (1 + i \, \tau_{shock} \, \frac{\partial}{\partial t})`$. If you take the Fourier transform of equation 2, the time derivative becomes $-i (\omega-\omega_0)$. Assuming the characteristic optical shock time scale of $\tau_{shock} = \tau_0 = 1/\omega_0$, this all simplifies to the following:
```math
\gamma \, (1 + \tau_0 \, (\omega - \omega_0)) = \gamma \frac{\omega}{\omega_0} = \left[\frac{\omega \, n_2}{c \, A_{eff}}\right]_{\omega=\omega_0} \frac{\omega}{\omega_0} = \frac{\omega}{c} \left[\frac{n_2}{A_{eff}}\right]_{\omega=\omega_0}
```
So the inclusion of the shock term simply restores the $\omega$ dependence of the frequency-domain $\gamma$ after the parameter was originally frozen at $\omega_0$. If you take Dudely's expanded definition of $\tau_{shock}$ from equation 3 (which includes terms for the effective index and effective area), you see that the shock term is related to the first derivative of $\gamma$ with respect to frequency, $`\tau_{shock} = \frac{1}{\gamma}\frac{\partial \gamma}{\partial \omega}_{\omega=\omega_0}`$. You can think of $\tau_{shock}$ as contributing the first term of the Taylor expansion of $\gamma$ about $\omega_0$, $`\gamma[\omega] \approx \gamma_0 + \gamma_1 \, (\omega - \omega_0) + \cdots`$. Using the full wavelength-dependence of $\gamma$ in your simulation is equivalent to extending the shock-term approximation to all orders. Just make sure you don't use the shock term and the wavelength-dependent $\gamma$ at the same time. You don't want to account for the same effect twice.

As Dan alluded to, it is possible to simulate fiber parameters that change with ``z`` if you call the ``set_dispersion_function``, ``set_gamma_function``, or ``set_alpha_function`` methods of the fiber object. Those expect to see functions with ``z`` as the only argument. If you don't want or need your parameters to change with ``z``, you don't have to define those functions. Just input the relevant arrays/parameters when you initialize the pulse object. In your code, you are already doing that for gamma, but you could do the same for the dispersion, i.e., use ``dispersion_format='n'`` and ``dispersion=(wls, neff_list)`` when you initialize the fiber.

**Comment by DanHickstein** [comment]
Connor! Thanks for the detailed information! It sounds like it should be pretty straightforward to implement the frequency-dependent gamma.

@elizaleung830, does what @cdfredrick and I are describing make sense to you? If not, I can try to make an example how how to incorporate a wavelength-dependent gamma.

**Comment by DanHickstein** [comment]
I mentioned this to David Carlson (@cardavr) today and he mentioned that he had implemented something similar following this paper. I haven't looked closely yet, but maybe it amounts to the same thing as what we are thinking of doing. 

[Kibler et al. - 2005 - Supercontinuum generation and nonlinear pulse prop.pdf](https://github.com/laserfun/laserfun/files/14069560/Kibler.et.al.-.2005.-.Supercontinuum.generation.and.nonlinear.pulse.prop.pdf)

![image](https://github.com/laserfun/laserfun/assets/1107796/494ddc62-967e-4b84-b22c-f78f532d00f4)

**Comment by elizaleung830** [comment]
Thanks for the help and it makes a lot more sense to me now! However when I call the w_THz property from the pulse, it is an array range from -3939 to 6354. I am not quite sure about what's the negative angular frequency means. 
![image](https://github.com/laserfun/laserfun/assets/87836029/48a622e8-b27f-4d15-be63-309c31da0086)

**Comment by cdfredrick** [comment]
Negative frequencies are an artifact of how the pulse is initialized. The step size of the time and frequency grids are constrained by the number of points, $`dt \, df = 1/N`$. For a given center wavelength, if you do not want negative frequencies (a good idea) then you need to reduce the frequency window $`\Delta f = N \, df`$. Either decrease the number of points or increase the time window, i.e., reduce the frequency step size $`df = 1/\Delta t`$.

**Comment by elizaleung830** [comment]
Thanks a lot!
